In [ ]:
#Numpy

In [ ]:
import numpy as np

In [ ]:
temperatures_w1 =np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]) #1D numpy array

In [ ]:
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
#inspection & properties

In [ ]:
print(temperatures_w1.shape) #Shape

(7,)


In [ ]:
print(temperatures_w1.dtype) #datatype

float64


In [ ]:
print(temperatures_w1.size) #Number of elements

7


In [ ]:
#Array operations

In [ ]:
T_Fahrenheit =(temperatures_w1*9/5)+32 #Convert celcuis to Fahrenheit

In [ ]:
print(T_Fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
print(np.max(temperatures_w1)) #Maximum

26.1


In [ ]:
print(np.min(temperatures_w1)) #Minimum

20.8


In [ ]:
print(np.mean(temperatures_w1)) #Mean

23.542857142857144


In [ ]:
#Array Slicing and Indexing

In [ ]:
print(temperatures_w1[:3]) #First 3 days of the week

[22.5 25.3 20.8]


In [ ]:
print(temperatures_w1[-2:]) #Last 2days

[24.8 21.9]


In [ ]:
print(temperatures_w1[2:5]) #Middle 3days

[20.8 23.4 26.1]


In [ ]:
#2D Array

In [ ]:
temperatures =np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

In [ ]:
#Inspect and Slice the 2D Array

In [ ]:
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
print(temperatures.shape)

(2, 7)


In [ ]:
print(temperatures.dtype)

float64


In [ ]:
print(temperatures.size)

14


In [ ]:
#Extract

In [ ]:
print(temperatures[0]) #1week

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
print(temperatures[1]) #2week

[19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [ ]:
print(temperatures[:,-2:]) #last 2 dys

[[24.8 21.9]
 [22.8 20.1]]


In [ ]:
#Pandas Series

In [ ]:
import pandas as pd

In [ ]:
marks =pd.Series([95, 92, 89, 85, 80],
                 index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

In [ ]:
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
#Indexing and Slicing

In [ ]:
print(marks[0])

95


/tmp/ipython-input-3296141910.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [ ]:
print(marks.loc[['Rank1','Rank2','Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
print(marks.iloc[2])

89


In [ ]:
print(marks[marks>90])

Rank1    95
Rank2    92
dtype: int64


In [ ]:
#Manipulating Series

In [ ]:
marks['Rank1']=100

In [ ]:
marks=marks.drop('Rank5')

In [ ]:
Cgpa=marks/10

In [ ]:
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
print(Cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
#Pandas Data frame

In [ ]:
transactions=pd.DataFrame({
    'TransactionID':[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],
 'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

In [ ]:
#Data Exploration

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [ ]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
print(transactions.shape)

(10, 4)


In [ ]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [ ]:
print(transactions.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [ ]:
print(transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
print(transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
print(transactions[(transactions['Region']=='North')&(transactions['Amount']>200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


In [ ]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [ ]:
#Manipulating the DataFrame

In [ ]:
transactions.loc[transactions['TransactionID']== 102 ,'Amount']=165

In [ ]:
print(transactions[1:-8])

   TransactionID ProductCategory Region  Amount
1            102        Clothing  South     165


In [ ]:
transactions['Discount']=transactions['Amount']*0.10

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions=transactions.drop(transactions[transactions['TransactionID']==109].index)

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions=transactions.drop('Discount',axis=1)

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
